#!/usr/bin/env ruby

require 'uri'
require 'pg'
require 'linodians'

TABLE_NAME = 'hellolinodians'
SCHEMA = [
  'id timestamp default CURRENT_TIMESTAMP',
  'data json NOT NULL'
]

uri = URI.parse(`heroku config:get DATABASE_URL`.strip)

host = uri.hostname
port = uri.port
db = uri.path[1..-1]
user = uri.user
password = uri.password

conn = PG.connect(host, port, nil, nil, db, user, password)
conn.exec("DROP TABLE IF EXISTS #{TABLE_NAME}")
conn.exec("CREATE TABLE #{TABLE_NAME} ( #{SCHEMA.join ', '} )")

puts 'Table created'
